question_data = {"response_code": 0
    , "results": [
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
         "incorrect_answers": ["False"]}
        , {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                                           "question": "According to Greek Mythology, Zeus can control lightning.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                          "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "Hungary is the only country in the world beginning with H.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                          "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                          "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.", "correct_answer": "True",
         "incorrect_answers": ["False"]}]}
